export const SSLCOMMERZ_INSTANCE = 'SSLCOMMERZ_INSTANCE';
export const SSLCOMMERZ_SUCCESS_URL = 'SSLCOMMERZ_SUCCESS_URL';
export const SSLCOMMERZ_FAIL_URL = 'SSLCOMMERZ_FAIL_URL';
export const SSLCOMMERZ_CANCEL_URL = 'SSLCOMMERZ_CANCEL_URL';
export const SSLCOMMERZ_IPN_URL = 'SSLCOMMERZ_IPN_URL';
export const SSLCOMMERZ_CONFIG = 'SSLCOMMERZ_CONFIG';
